# Generated by Django 5.0.1 on 2024-03-14 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Номер телефона')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('confirmation_token', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(upload_to='media')),
                ('subscription_start_date', models.DateField(blank=True, null=True)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
                ('subscription_info', models.BooleanField(blank=True, default=True, null=True, verbose_name='Подписка на уведомления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
